JuliaML/MLDatasets.jl

- .travis.yml
- README.md
- REQUIRE
- docs/make.jl
- docs/src/datasets/SVHN2.md
- docs/src/index.md
- src/MLDatasets.jl
- src/SVHN2/SVHN2.jl
- src/SVHN2/interface.jl
- src/SVHN2/utils.jl
- test/runtests.jl
- test/tst_svhn2.jl
I am working on integrating the [street view house numbers](http://ufldl.stanford.edu/housenumbers/) dataset. 
A big downside is that the data is provided in `.mat` format at the official website. This means that we would need to add a dependency on `MAT.jl` which requires `HDF5.jl`. Aside from the binary dependency it is also less convenient to work with. For starters one needs to read the whole file and can just cherry pick specific observations.
> WIP: add SVHN dataset (Format 2)

- REQUIRE
- src/CIFAR10/CIFAR10.jl
- src/CIFAR100/CIFAR100.jl
- src/FashionMNIST/FashionMNIST.jl
- src/MNIST/MNIST.jl
- src/PTBLM/PTBLM.jl
- src/UD_English/UD_English.jl
addresses the following warning:
```julia
WARNING: RegisterDataDep(name::String, message::String, remotepath, hash=nothing; fetch_method=download, post_fetch_method=identity) is deprecated, use register(DataDep(name::String, message::String, remotepath, hash; fetch_method=fetch_method, post_fetch_method=post_fetch_method)) instead.
```
> fix RegisterDataDep deprecation

- .travis.yml
- REQUIRE
- docs/make.jl
- docs/src/LICENSE.md
- src/CIFAR10/CIFAR10.jl
- src/CIFAR10/utils.jl
- src/CIFAR100/CIFAR100.jl
- src/FashionMNIST/FashionMNIST.jl
- src/MLDatasets.jl
- src/MNIST/MNIST.jl
- src/MNIST/utils.jl
- src/SVHN2/SVHN2.jl
- src/SVHN2/interface.jl
- src/SVHN2/utils.jl
- src/download.jl
- test/REQUIRE
- test/tst_cifar10.jl
- test/tst_cifar100.jl
- test/tst_fashion_mnist.jl
- test/tst_mnist.jl
- test/tst_svhn2.jl
This PR (extracted from #20) makes ImageCore.jl and MAT.jl packages optional (via [Requires.jl](https://github.com/MikeInnes/Requires.jl)). These packages bring with them tons of other dependencies, while the functionality they provide is not essential. ImageCore and MAT are still required for unit testing. If ImageCore and/or MAT are added to a specific Julia project, the corresponding MLDatasets functions (converting to images and SVHN2 dataset) would be automatically enabled.
As a samll added bonus it should fix Documenter scripts.
> Make ImageCore and MAT packages optional

- README.md
- src/EMNIST/EMNIST.jl
- src/MLDatasets.jl
- test/runtests.jl
- test/tst_emnist.jl
Fixes #51
I think I have properly included all the data and functionality needed to integrate EMNIST into the package. It passed all tests.
I wrote very little fancy functionality and barebones tests/documentation. I plan to add rotMNIST soon and will try to improve things then time allowing. I really wanted the different datasets packaged in EMNIST to be called like EMNIST.byclass.traindata() etc. I am not sure how I implemented was the cleanest way possible, just creating a whole bunch of submodules. If you have advice on better ways to do this (passing functions outside the module inside so I do not have to redefine it every time, as well as having the using modules propagate), that would be great for future reference.
Super open to suggestions and feedback. This is my first PR in …
> Include EMNIST

- Project.toml
- src/MNIST/MNIST.jl
Fix #57 using the mirror offered by pytorch vision (https://github.com/pytorch/vision/pull/3544)
@johnnychen94
> change MNIST download links

- README.md
As suggested in https://github.com/JuliaML/MLDatasets.jl/issues/74
(However, personally I believe it is better to point new users to the "stable" documentation branch, i.e. those that correspond to "add  PkgX")
> Update links to datasets documentation in the homepage

- src/Mutagenesis/Mutagenesis.jl
- test/tst_mutagenesis.jl
This commits removes labels from features, because previously the labels were part of the features, which is fundamentally wrong. 
Data is materialized as a side-effect, because JSON3 does not provide a way to lazily delete this, but it should not be problem since the dataset is very small.
> removing labels from features

- docs/make.jl
it can currently only be discovered on the readme.
> add EMNIST in the docs sidebar

- .github/workflows/UnitTest.yml
Since macOS 12 is not available, let's at least get macOS 11 in here: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#github-hosted-runners
> Update UnitTest.yml to add macOS 11

- src/containers/cacheddataset.jl
Fixing broken precompilation
```julia
julia> using MLDatasets
[ Info: Precompiling MLDatasets [eb30cadb-4394-5ae3-aed4-317e484a6458]
WARNING: Method definition (::Type{MLDatasets.CachedDataset{T, S} where S where T})(Any) in module MLDatasets at /home/carlo/.julia/dev/MLDatasets/src/containers/cacheddataset.jl:29 overwritten at /home/carlo/.julia/dev/MLDatasets/src/containers/cacheddataset.jl:31.
** incremental compilation may be fatally broken for this module **
```
> fix CachedDataset breaking precompilation

- src/Titanic/Titanic.jl
- test/tst_titanic.jl
resolves #108 
Changes:
1. Use `permutedims` instead of `reshape` to ensure that the order of the elements stay the same
2. Add a new test case that checks whether the first row in the returned matrix is the correct one.
> Fixed matrix order in Titanic features

- src/MLDatasets.jl
The "core" packages should still be loaded eagerly, otherwise, we'll hit a lot of world-age issues like #135.
closes #135
cc: @Dsantra92
> eagerly load CSV

- src/datasets/graphs/ogbdataset.jl
Fix errors that appear for Datasets like ogbl-collab where the zip name is collab.zip. So `mv` command throws an error in this case:
```julia
ArgumentError: '/home/deebyo/.julia/datadeps/OGBDataset/collab' exists. `force=true` is required to remove '/home/deebyo/.julia/datadeps/OGBDataset/collab' before moving.
```
> Fix unzip errors in OGB-Datasets

- docs/src/datasets/graphs.md
- src/datasets/graphs/ogbdataset.jl
- src/graph.jl
- test/datasets/graphs.jl
Handling Hetero Graphs in OGBDatasets.
> Support for OGB Hetero-Graphs

- src/datasets/vision/cifar10.jl
- src/datasets/vision/cifar100.jl
- src/datasets/vision/emnist.jl
- src/datasets/vision/mnist.jl
- src/datasets/vision/svhn2.jl
An extra colon seems to have snuck into the documentation string for most of the vision datasets.
That is all.
> Fix documentation typos for vision datasets

- src/datasets/graphs/movielens.jl
- test/datasets/graphs_no_ci.jl
The 10m dataset seems to have some weird entries that mess up parsing with quotes, so I turned it off for that one.
Should finally fix issue #151.
> Fix movielens 10m

- src/datasets/graphs/ogbdataset.jl
- src/graph.jl
- test/datasets/graphs.jl
- test/runtests.jl
The pr adds support for simple graph link split (#107) as well as support for splits in Heterogeneous OGB Datasets.
Need Fixing before merge: #167
> Split for OGBDatasets 

- src/MLDatasets.jl
- src/io.jl
- test/runtests.jl
Moving `Pickle` to required packages. This means we have to load `Pickle` explicitly for Planetoid graph datasets.
> require explicit Pickle import in load_pytorch

- src/abstract_datasets.jl
The specific behavior of the `as_df` keyword stated in the docstring template for specific fields is contrary to the keyword's main description, the keyword meaning and to its actual behavior: `as_df=false` for plain arrays, `as_df=true` for dataframes.
> Corrects docstring for the `as_df` keyword

- src/datasets/graphs/tudataset.jl
- test/datasets/graphs.jl
Our `TUDataset` implementation didn't support a node, edge or graph having multiple labels. A simple change in delimiter allows us to read all the labels correctly. Ideally closes #195 
ToDo:
> Support multiple labels for nodes, edges and graphs

- src/datasets/graphs/ogbdataset.jl
There are some missing value in OGB master CSVs. This pr aims to handle missing value for creating metadata.
Fix: #201
> Handle missing values in OGB master csv

- docs/src/datasets/graphs.md
- src/MLDatasets.jl
- src/datasets/graphs/metrla.jl
- src/datasets/graphs/pemsbay.jl
- src/datasets/graphs/traffic.jl
- test/datasets/graphs_no_ci.jl
This PR adds the traffic dataset PEMS-BAY. I created a common script contained in `traffic.jl` that is used by both the PEMS-BAY and METR-LA traffic datasets.
> Add PEMS-BAY dataset

- docs/src/datasets/graphs.md
- src/MLDatasets.jl
- src/datasets/graphs/temporalbrains.jl
- test/datasets/graphs_no_ci.jl
This PR adds the `TemporalBrains` dataset,  a collection of temporal brain networks of 1000 subjects obtained from resting-state fMRI data.
> Add TemporalBrains dataset

- Project.toml
- docs/src/datasets/graphs.md
- src/MLDatasets.jl
- src/datasets/graphs/windmillenergy.jl
- test/datasets/graphs_no_ci.jl
This PR adds the WindMillEnergy graph dataset contained in [Pytorch Geometric Temporal](https://pytorch-geometric-temporal.readthedocs.io/en/latest/module/dataset.html#torch_geometric_temporal.dataset.windmilllarge.WindmillOutputLargeDatasetLoader)
> Add WindMillEnergy dataset
